watch:
  schedule: "0 8 * * *"  # Check daily at 8am
  firstCheckNotif: false

providers:
  docker:
    watchByDefault: true
    watchStopped: false

notif:
  telegram:
    token: "{{ .Env.DIUN_TELEGRAM_TOKEN }}"
    chatIDs:
      - {{ .Env.DIUN_TELEGRAM_CHAT_ID }}
